management.health.circuitbreakers.enabled: true
management.health.ratelimiters.enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: TIME_BASED
        waitDurationInOpenState: 50s
        minimumNumberOfCalls: 10
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
          - java.lang.Exception
    instances:
      myCircuitBreaker:
        baseConfig: default
  retry:
    configs:
      default:
        waitDuration: 10s
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - java.io.IOException
          - java.lang.Exception
    instances:
      myCircuitBreaker:
        baseConfig: default
  bulkhead:
    configs:
      default:
        maxWaitDuration: 10ms
        maxConcurrentCalls: 10
    instances:
      myCircuitBreaker:
        baseConfig: default
  ratelimiter:
    configs:
      default:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0
        registerHealthIndicator: true
    instances:
      myCircuitBreaker:
        baseConfig: default
  timelimiter:
    instances:
      myCircuitBreaker:
        cancelRunningFuture: false
        timeoutDuration: 5s
